// Static asset server only — all content is pre-generated by the weekly
// GitHub Actions job and committed as public/feed.json and public/comics.json.
export default {
  async fetch(request, env) {
    if (env.ASSETS) return env.ASSETS.fetch(request)
    return new Response('Not found', { status: 404 })
  }
}
